import { Sora } from "next/font/google";
import "@/app/(site)/globals.css"
import AdminNav from "../../components/AdminNav";
import AdminMenuContextProvider from "../../AdminContext";
import MenuContextProvider from "../../MenuContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Bounce } from "react-toastify";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({ children, termekszerkeszto, termekkategoriak, termekcimkek, blogok, blogcimkek, blogkategoriak, rendelesek, oldalkeszito, slider, hirdetesek, vasarlok, kuponok, velemenyek, felhasznalok, pontok }) {
  return (
    <html lang="en">
      <MenuContextProvider>
        <AdminMenuContextProvider>
          <body className={`${sora.className}`}>
            <ToastContainer
              position="bottom-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              theme="light"
              transition={Bounce}
            />
            <AdminNav />
            {children}
            {termekszerkeszto}
            {termekkategoriak}
            {termekcimkek}
            {blogok}
            {blogcimkek}
            {blogkategoriak}
            {rendelesek}
            {oldalkeszito}
            {slider}
            {hirdetesek}
            {vasarlok}
            {kuponok}
            {velemenyek}
            {felhasznalok}
            {pontok}
          </body>
        </AdminMenuContextProvider>
    </html>
  );
}
