import { Sora } from "next/font/google";
import "./globals.css";
import MenuContextProvider from "../MenuContext";
import { CartUIProvider } from "../components/cart/CartUIProvider";
import CartDrawer from "../components/cart/CartDrawer";
import { FavoritesUIProvider } from "../components/favorites/FavoritesUIProvider";
import FavoritesDrawer from "../components/favorites/FavoritesDrawer";
import { CompareUIProvider } from "../components/compare/CompareUIProvider";
import CompareDrawer from "../components/compare/CompareDrawer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Bounce } from "react-toastify";
import MainNav from "../components/Mainnav";
import ScrollToTopButton from "../components/ScrollToTopButton";
import Footer from "@/app/components/Footer"

import UserMenuDrawer from "../components/UserMenuDrawer";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${sora.className}`}>
        <MenuContextProvider>
          <CartUIProvider>
            <FavoritesUIProvider>
              <CompareUIProvider>
                <ToastContainer
                  position="top-center"
                  autoClose={3000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick={false}
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  theme="light"
                  transition={Bounce}
                />
                <MainNav />
                {children}
                <Footer />
                <CartDrawer />
                <FavoritesDrawer />
                <CompareDrawer />
                <UserMenuDrawer />
                <ScrollToTopButton />
              </CompareUIProvider>
            </FavoritesUIProvider>
          </CartUIProvider>
        </MenuContextProvider>
      </body>
    </html>
  );
}
