import { Sora } from "next/font/google";
import "./globals.css";
import MainNav from "@/app/components/MainNav";
import MenuContextProvider from "../MenuContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Bounce } from "react-toastify";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${sora.className}`}>
        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          theme="light"
          transition={Bounce}
        />
        <MenuContextProvider>
          <MainNav />
        </MenuContextProvider>
        {children}
      </body>
    </html>
  );
}
