import { Sora } from "next/font/google";
import "./globals.css";
import Mainnav from "./components/Mainnav";
import MenuContextProvider from "./MenuContext";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sora.className}`}>
        <MenuContextProvider>
          <Mainnav/>
        </MenuContextProvider>
        {children}
      </body>
    </html>
  );
}