import { Sora } from "next/font/google";
import "../(site)/globals.css";
import AdminNav from "../components/AdminNav";
import AdminMenuContextProvider from "../AdminContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Bounce } from "react-toastify";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({ children, modals }) {
  return (
    <html lang="en">
      <AdminMenuContextProvider>
      <body className={`${sora.className}`}>
        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          theme="light"
          transition={Bounce}
        />
        
          <AdminNav />
        
        {children}
        {modals}
      </body>
      </AdminMenuContextProvider>
    </html>
  );
}
